/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.SmartWatch;
import java.awt.Color;

/**
 *
 * @author smsta
 */
public class SmartWatchGUI extends javax.swing.JFrame {
    
    private SmartWatch smartWatch;

    /**
     * Creates new form SmartWatchGUI
     */
    public SmartWatchGUI() {
        setAlwaysOnTop(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        smartWatchLED = new javax.swing.JLabel();
        smartWatchLEDText = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagesTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        waterLED = new javax.swing.JLabel();
        waterLabel = new javax.swing.JLabel();
        smokeLED = new javax.swing.JLabel();
        smokeLabel = new javax.swing.JLabel();
        windowLabel = new javax.swing.JLabel();
        doorLED = new javax.swing.JLabel();
        doorLabel = new javax.swing.JLabel();
        GasLabel = new javax.swing.JLabel();
        GasLED1 = new javax.swing.JLabel();
        windowLED2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Watch");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        rootPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upperPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        upperPanel.setForeground(new java.awt.Color(255, 0, 0));

        smartWatchLED.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        smartWatchLED.setForeground(new java.awt.Color(255, 0, 0));
        smartWatchLED.setText("•");

        smartWatchLEDText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        smartWatchLEDText.setText("Smart Watch is not running");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(smartWatchLED)
                .addGap(28, 28, 28)
                .addComponent(smartWatchLEDText, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addComponent(smartWatchLED, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smartWatchLEDText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startButton))
                .addContainerGap())
        );

        rootPanel.add(upperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 50));

        bottomPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bottomPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messagesTextArea.setEditable(false);
        messagesTextArea.setColumns(20);
        messagesTextArea.setRows(5);
        messagesTextArea.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(messagesTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 507, 250));

        bottomPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(70, 208));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        waterLED.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        waterLED.setForeground(new java.awt.Color(255, 0, 51));
        waterLED.setText("•");
        jPanel2.add(waterLED, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 68, 49));

        waterLabel.setText("Water");
        jPanel2.add(waterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 1, 68, 49));

        smokeLED.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        smokeLED.setForeground(new java.awt.Color(255, 0, 51));
        smokeLED.setText("•");
        jPanel2.add(smokeLED, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 68, 49));

        smokeLabel.setText("Smoke");
        jPanel2.add(smokeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 68, 49));

        windowLabel.setText("Window");
        jPanel2.add(windowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 68, 49));

        doorLED.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        doorLED.setForeground(new java.awt.Color(255, 0, 51));
        doorLED.setText("•");
        jPanel2.add(doorLED, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 68, 49));

        doorLabel.setText("Door");
        jPanel2.add(doorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 68, 49));

        GasLabel.setText("Gas");
        jPanel2.add(GasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        GasLED1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        GasLED1.setForeground(new java.awt.Color(255, 0, 51));
        GasLED1.setText("•");
        jPanel2.add(GasLED1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 68, 49));

        windowLED2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        windowLED2.setForeground(new java.awt.Color(255, 0, 51));
        windowLED2.setText("•");
        jPanel2.add(windowLED2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 68, 49));

        bottomPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 1, 204, 250));

        rootPanel.add(bottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 730, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        smartWatch = new SmartWatch(this);
        
        new SmartWatchingRunning().start();
        startButton.setEnabled(false);
        smartWatchLED.setForeground(Color.green);
        smartWatchLEDText.setText("Smart Watch is active");
    }//GEN-LAST:event_startButtonActionPerformed
    
    public void appendToTextArea(String str) {
        messagesTextArea.append(str);
        messagesTextArea.setCaretPosition(messagesTextArea.getText().length() - 1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartWatchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartWatchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartWatchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartWatchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SmartWatchGUI().setVisible(true);
        });
    }
    
    public void smartWatchLEDColors(boolean water, boolean smoke, boolean window, boolean door , boolean gas) {
        if (!door) {
            doorLED.setForeground(Color.red);
        } else {
            doorLED.setForeground(Color.green);
        }
        if (!window) {
            windowLED2.setForeground(Color.red);
        } else {
            windowLED2.setForeground(Color.green);
        }
        if (!water) {
            waterLED.setForeground(Color.red);
        } else {
            waterLED.setForeground(Color.green);
        }
        if (!smoke) {
            smokeLED.setForeground(Color.red);
        } else {
            smokeLED.setForeground(Color.green);
        }
        if ( !gas ) {
            GasLED1.setForeground(Color.red);   
        } else {
              GasLED1.setForeground(Color.green);
        }
    }
    
    class SmartWatchingRunning extends Thread {
        
        @Override
        public void run() {
            smartWatch.start();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GasLED1;
    private javax.swing.JLabel GasLabel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JLabel doorLED;
    private javax.swing.JLabel doorLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messagesTextArea;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JLabel smartWatchLED;
    private javax.swing.JLabel smartWatchLEDText;
    private javax.swing.JLabel smokeLED;
    private javax.swing.JLabel smokeLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel waterLED;
    private javax.swing.JLabel waterLabel;
    private javax.swing.JLabel windowLED2;
    private javax.swing.JLabel windowLabel;
    // End of variables declaration//GEN-END:variables

}
